### ISSUE TITLE
custom fields search

### ISSUE THREAD

**Issue by soukupl** [WebberZone/better-search#1]
hello,
thanks for the great search plugin :)
On our site (uplnezneni.cz) I would like to have an option to use custom fields as part of search query with higher relevance than main content. Site contains full text of laws and we have several custom keywords in the custom fields as text of law is not search engine friendly and can't be changed.

Or, is there any hook I can use to modify the db query to add search rules for custom fields?

Thanks :)

**Comment by ajaydsouza** [comment]
It took me a long time to respond to this, but, I've had a chance to play with custom fields particularly in a WooCommerce perspective. 

Check out this gist which has an example of how you can do so: https://gist.github.com/ajaydsouza/767215093a24bafb903a

Obviously, there is a lot more that would need to go in to make it searchable. e.g. potentially LIKE statements for the contents of the fields.

**Comment by ajaydsouza** [comment]
This has been implemented in v3.0.0 where the plugin will search for results in meta values if enabled in the settings page.

https://github.com/WebberZone/better-search/releases/tag/v3.0.0-beta2
