### ISSUE TITLE
Exclude post IDs

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/better-search#11]
Add an option to exclude post IDs from showing up in the results

**Comment by BinaryKitten** [comment]
Can this be extended with a filter please. so that the settings page can be extended within theme code etc.

**Comment by ajaydsouza** [comment]
@BinaryKitten, the new settings API implementation in the repository (to be released in v2.2.0) will allow anyone to extend the settings

I've also implemented this feature in: https://github.com/WebberZone/better-search/commit/61de6f731c767cb3a244a446c18c834991c544cc
