### ISSUE TITLE
Post types to include doesn't work

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/better-search#114]
In seamless mode, all the post types are searched instead of just the selected one. Seems okay with seamless mode off.

**Comment by alihs** [comment]
It seems that this even completed, doesn't work. 
Results bring CPTs that are unchecked.

**Comment by ajaydsouza** [comment]
Can you please get me the queries from Query Monitor on your search results page? Also, please can you resave settings with the cache setting off before you do.
