### ISSUE TITLE
Fatal error because of hardcoded wp-load.php

### ISSUE THREAD

**Issue by dmbostan** [WebberZone/better-search#38]
This line fails, because of a hardcoded path:

https://github.com/WebberZone/better-search/blob/master/includes/better-search-addcount.js.php#L14

Is there a workaround for it?

**Comment by ajaydsouza** [comment]
Where exactly do you have the file saved in your install?

My experience has been typically in the main directory where WordPress is installed or one level higher.

**Comment by dmbostan** [comment]
I am using WP as a composer dependency, and normally would be: /app/wp

**Comment by ajaydsouza** [comment]
Understood - you won't be able to do it easily with the current plugin - for now, can you edit the hardcoded path to correctly reflect the location of your wp-load.php

I'll explore an alternative tracker that is more automatic but ends up being slower as you lose the SHORTINIT ability.

**Comment by dmbostan** [comment]
That is an issue as I am loading the plugin as a composer dependency, as well.

Can't that just be refactored to use WP Ajax instead of wp-load.php? 

It will decrease the heavy loading and you full have access to all WP functions?

**Comment by ajaydsouza** [comment]
That is the plan - either WP Ajax or using Query variables.

**Comment by ajaydsouza** [comment]
v2.2.4 has just been released which implements the tracking without the need for wp-load. It uses query variables and ajax

**Comment by dmbostan** [comment]
Thank you, @ajaydsouza !
