### ISSUE TITLE
Better search & replace no longer functions on my wordpress site. Quite simply nothing happens when I try to make replacements. The scores come up as zero no matter what

### ISSUE THREAD

**Issue by marmadale** [WebberZone/better-search#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajaydsouza** [comment]
You have the wrong plugin. This is Better Search. You are referring to Better Search and Replace.
