### ISSUE TITLE
A blank search term and a space as a term

### ISSUE THREAD

**Issue by chaaacha** [WebberZone/better-search#71]
hi,
Thanks for the plugin it works really well
I have encountered such a problem and would love a solution
I marked 2 categories that I do not want to be included in the search and they really are not found except when I am looking for a space or empty search
I would love a quick solution

thanks again

**Comment by ajaydsouza** [comment]
Please raise a query in the support forum as GitHub is for bugs reporting and not support. If this ends up being a bug, I’ll reopen this issue with a filing of that.

Thanks.
